version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-ecs: circleci/aws-ecs@0.0.10
jobs:
  update-tag:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/install
      - aws-cli/setup:
          profile-name: default
      - checkout
      - aws-ecs/update-service:
          family: '$proxy-service'
          cluster-name: '$proxy-cluster'
          container-image-name-updates: 'container=$proxy-service,tag=stable'
workflows:
  deploy:
    jobs:
      - update-tag
