version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    machine:
       enabled: true
    steps:
      - run:
          name: Deploy
          command: |
            # - SSH to the server to deploy
            EC2_USERNAME=ec2-user
            EC2_PUBLIC_DNS=ec2-3-101-79-33.us-west-1.compute.amazonaws.com
            echo 'using SSH to connect to EC2'
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "cd hugo-proxy; git pull; npm i; pm2 restart proxy"
            echo 'disconnected from SSH'

workflows:
   test-and-deploy:
     jobs:
       - node/test
       - deploy:
           requires:
             - node/test # only deploy once test job has completed
           filters:
             branches:
               only: master # only deploy on the master branch
