version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  deploy-ec2:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
workflows:
  node-tests:
    jobs:
      - node/test
  deploy:
    jobs:
      - deploy-ec2
      
      
      
