version: 2.1
jobs:
  deploy:
    machine:
       enabled: true
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # - SSH to the server to deploy
            # Change to your username
            EC2_USERNAME=ec2-user
            # Change to your server's URL or public IP
            EC2_PUBLIC_DNS=ec2-54-215-231-37.us-west-1.compute.amazonaws.com
            echo 'using SSH to connect to EC2'
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "ls -al"
            echo 'disconnected from SSH'
                
workflows:
   build-and-deploy:
     jobs:
       - deploy
#        - deploy:
#            requires:
#              - build # only deploy once build job has completed
#            filters:
#              branches:
#                only: master # only deploy on the master branch
