version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@1.3.0
jobs:
#   deploy:
#     docker:
#       - image: 'circleci/python:3.7.1'
#     steps:
#       - checkout
#       - aws-cli/install
#       - aws-cli/setup:
#           profile-name: default
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # 7- SSH to the server to deploy
            # TODO Change to your username
            EC2_USERNAME=ec2-user
            # TODO Change to your server's URL or public IP
            EC2_PUBLIC_DNS=ec2-54-215-231-37.us-west-1.compute.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS
            echo 'Start deploy'
            ls -al
            cd hugo-proxy
            git pull
            npm i
            pm2 restart proxy
            echo 'Stop deploy'
            exit
                
workflows:
  deploy:
    jobs:
      - build
