version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"
  deploy-ec2:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node -v
workflows:
  node-tests:
    jobs:
      - node/test
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
  deploy:
    jobs:
      - deploy-ec2
