version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  deploy-ec2:
    macos: # this is supposed to be executor -- commands execute in macOS container
    steps:
      - run: echo "Hi - print something"
workflows:
  node-tests:
    jobs:
      - node/test
  deploy:
    jobs:
      - deploy-ec2
      
      
      
