version: 2.1
orbs:
  node: circleci/node@3.0.0
aws-ecs: circleci/aws-ecs@1.3.0
jobs:
  deploy-ec2:
    steps:
      - # first step in deployment
workflows:
  node-tests:
    jobs:
      - node/test
  deploy:
    jobs:
      - deploy-ec2
      
      
      
